---
- name: Universal Package Manager Maintenance
  hosts: all
  gather_facts: yes
  become: yes
  
  pre_tasks:
    - name: Display system information
      debug:
        msg: "Detected {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }})"
    
    - name: Display start message
      debug:
        msg: "Starting package maintenance at {{ ansible_date_time.iso8601 }}"
    
    - name: Initialize detected package managers list
      set_fact:
        detected_pkg_managers: []
    
    - name: Detect APT
      set_fact:
        detected_pkg_managers: "{{ detected_pkg_managers + ['apt'] }}"
      when: ansible_os_family == 'Debian'
    
    - name: Detect DNF
      set_fact:
        detected_pkg_managers: "{{ detected_pkg_managers + ['dnf'] }}"
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8
    
    - name: Detect DNF for Fedora
      set_fact:
        detected_pkg_managers: "{{ detected_pkg_managers + ['dnf'] }}"
      when: ansible_distribution == 'Fedora'
    
    - name: Detect YUM
      set_fact:
        detected_pkg_managers: "{{ detected_pkg_managers + ['yum'] }}"
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 7
    
    - name: Detect Zypper
      set_fact:
        detected_pkg_managers: "{{ detected_pkg_managers + ['zypper'] }}"
      when: ansible_os_family == 'Suse'
    
    - name: Detect Pacman
      set_fact:
        detected_pkg_managers: "{{ detected_pkg_managers + ['pacman'] }}"
      when: ansible_os_family == 'Archlinux'
    
    - name: Check for Flatpak
      command: which flatpak
      register: flatpak_check
      failed_when: false
      changed_when: false
    
    - name: Check for Snap
      command: which snap
      register: snap_check
      failed_when: false
      changed_when: false
  
  roles:
    # Native package managers
    - role: apt_maintenance
      when: "'apt' in detected_pkg_managers"
      tags: [apt, native]
    
    - role: dnf_maintenance
      when: "'dnf' in detected_pkg_managers"
      tags: [dnf, native]
    
    - role: yum_maintenance
      when: "'yum' in detected_pkg_managers"
      tags: [yum, native]
    
    - role: zypper_maintenance
      when: "'zypper' in detected_pkg_managers"
      tags: [zypper, native]
    
    - role: pacman_maintenance
      when: "'pacman' in detected_pkg_managers"
      tags: [pacman, native]
    
    # Universal package managers
    - role: flatpak_maintenance
      when: flatpak_check.rc == 0
      tags: [flatpak, universal]
    
    - role: snap_maintenance
      when: snap_check.rc == 0
      tags: [snap, universal]
  
  post_tasks:
    - name: Display completion message
      debug:
        msg: "Package maintenance completed at {{ ansible_date_time.iso8601 }}"
    
    - name: Display maintenance summary
      debug:
        msg: 
          - "Maintained package managers:"
          - "  Native: {{ detected_pkg_managers | join(', ') if detected_pkg_managers | length > 0 else 'none' }}"
          - "  Flatpak: {{ 'yes' if flatpak_check.rc == 0 else 'no' }}"
          - "  Snap: {{ 'yes' if snap_check.rc == 0 else 'no' }}"