---
- name: YUM maintenance start
  debug:
    msg: "Starting YUM maintenance (RHEL/CentOS 7)"

- name: Update YUM cache
  yum:
    update_cache: yes
  register: yum_cache

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest
  register: yum_upgrade

- name: Show upgraded packages count
  debug:
    msg: "Upgraded packages via YUM"
  when: yum_upgrade.changed

- name: Remove unnecessary packages (autoremove)
  yum:
    autoremove: yes
  register: yum_autoremove

- name: Clean YUM cache
  yum:
    name: "*"
    state: latest
    update_cache: yes
  changed_when: false

- name: YUM maintenance complete
  debug:
    msg: "YUM maintenance completed"