---
- name: Snap maintenance start
  debug:
    msg: "Starting Snap maintenance"

- name: Refresh Snap packages
  command: snap refresh
  register: snap_refresh
  changed_when: "'All snaps up to date' not in snap_refresh.stdout"

- name: Show snap refresh status
  debug:
    msg: "{{ snap_refresh.stdout_lines }}"
  when: snap_refresh.changed

- name: Remove disabled snaps
  shell: snap list --all | awk '/disabled/{print $1, $3}' | while read snapname revision; do snap remove "$snapname" --revision="$revision"; done
  register: snap_cleanup
  changed_when: snap_cleanup.stdout != ""
  failed_when: false

- name: Snap maintenance complete
  debug:
    msg: "Snap maintenance completed"
