---
- name: APT maintenance start
  debug:
    msg: "Starting APT maintenance (Debian/Ubuntu/Mint)"

- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade packages
  apt:
    upgrade: dist
  register: apt_upgrade

- name: Show upgraded packages status
  debug:
    msg: "APT packages upgraded"
  when: apt_upgrade.changed

- name: Remove unnecessary packages
  apt:
    autoremove: yes
    purge: yes
  register: apt_autoremove

- name: Clean APT cache
  apt:
    autoclean: yes

- name: APT maintenance complete
  debug:
    msg: "APT maintenance completed"