---
- name: Pacman maintenance start
  debug:
    msg: "Starting Pacman maintenance (Arch Linux/Manjaro)"

- name: Update package database and upgrade all packages
  pacman:
    update_cache: yes
    upgrade: yes
  register: pacman_upgrade

- name: Show upgraded packages count
  debug:
    msg: "Upgraded packages via Pacman"
  when: pacman_upgrade.changed

- name: Get list of orphaned packages
  command: pacman -Qtdq
  register: pacman_orphans
  changed_when: false
  failed_when: false

- name: Remove orphaned packages
  command: pacman -Rns --noconfirm {{ pacman_orphans.stdout_lines | join(' ') }}
  when: pacman_orphans.rc == 0 and pacman_orphans.stdout_lines | length > 0
  register: pacman_autoremove

- name: Check if paccache is available
  command: which paccache
  register: paccache_check
  changed_when: false
  failed_when: false

- name: Clean package cache (keep latest 3 versions)
  command: paccache -rk3
  when: paccache_check.rc == 0
  register: pacman_cache_clean
  changed_when: true
  failed_when: false

- name: Clean uninstalled package cache
  command: paccache -ruk0
  when: paccache_check.rc == 0
  changed_when: true
  failed_when: false

- name: Pacman maintenance complete
  debug:
    msg: "Pacman maintenance completed"