---
# Elasticsearch Installation and Configuration Role
# Based on tested installation: ELK_INSTALLATION_LOG.md Steps 2-5

- name: Import Elasticsearch GPG key
  rpm_key:
    key: "{{ gpg_key_url }}"
    state: present
  tags:
    - elasticsearch
    - repository

- name: Create Elasticsearch repository configuration
  copy:
    content: |
      [elastic-8.x]
      name=Elastic repository for 8.x packages
      baseurl={{ elastic_repo_baseurl }}
      gpgcheck=1
      gpgkey={{ gpg_key_url }}
      enabled=1
      autorefresh=1
      type=rpm-md
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: '0644'
  tags:
    - elasticsearch
    - repository

- name: Install Elasticsearch
  dnf:
    name: elasticsearch
    state: present
  register: es_install
  notify: restart elasticsearch
  tags:
    - elasticsearch
    - packages

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  tags:
    - elasticsearch
    - services

- name: Enable and start Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
  register: es_start
  tags:
    - elasticsearch
    - services

- name: Wait for Elasticsearch to initialize
  pause:
    seconds: 20
  when: es_install.changed
  tags:
    - elasticsearch

- name: Check if password was auto-generated in logs
  shell: |
    set -o pipefail
    grep -i "generated password for the elastic built-in superuser" /var/log/elasticsearch/elasticsearch.log 2>/dev/null | \
    tail -1 | \
    sed -E 's/.*superuser is : //; s/.*superuser is: //' | \
    awk '{print $1}' || echo "PASSWORD_NOT_FOUND"
  register: es_password_check
  changed_when: false
  no_log: true
  tags:
    - elasticsearch
    - credentials

- name: Reset Elasticsearch password (if not auto-generated)
  shell: |
    /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -b
  register: es_password_reset
  changed_when: true
  no_log: true
  when:
    - es_install.changed
    - es_password_check.stdout == "PASSWORD_NOT_FOUND"
  tags:
    - elasticsearch
    - credentials

- name: Extract password from reset output
  set_fact:
    elasticsearch_password: "{{ es_password_reset.stdout | regex_search('New value: (.+)', '\\1') | first }}"
  no_log: true
  when:
    - es_password_reset is defined
    - es_password_reset.stdout is defined
    - es_password_reset.stdout | length > 0
  tags:
    - elasticsearch
    - credentials

- name: Use auto-generated password if it exists
  set_fact:
    elasticsearch_password: "{{ es_password_check.stdout }}"
  no_log: true
  when:
    - es_password_check.stdout != "PASSWORD_NOT_FOUND"
    - es_password_check.stdout | length > 0
  tags:
    - elasticsearch
    - credentials

- name: Persist Elasticsearch password across roles
  set_stats:
    data:
      elasticsearch_password: "{{ elasticsearch_password }}"
  no_log: true
  when: elasticsearch_password is defined
  tags:
    - elasticsearch
    - credentials

- name: Display password capture status
  debug:
    msg: "Elasticsearch password {{ 'set successfully' if elasticsearch_password is defined else 'FAILED - manual intervention required' }}"
  tags:
    - elasticsearch
    - credentials

- name: Wait for Elasticsearch to be ready
  uri:
    url: "https://localhost:{{ elasticsearch_port }}"
    method: GET
    user: elastic
    password: "{{ elasticsearch_password | default(lookup('env', 'ES_PASSWORD')) }}"
    validate_certs: no
    status_code: 200
  retries: 15
  delay: 4
  register: es_health
  until: es_health.status == 200
  ignore_errors: yes
  when: elasticsearch_password is defined
  tags:
    - elasticsearch
    - health-check

- name: Persist Elasticsearch health status across roles
  set_stats:
    data:
      es_is_ready: "{{ es_health.status == 200 if es_health.status is defined else false }}"
  when: es_health is defined
  tags:
    - elasticsearch
    - health-check
