---
- name: Zypper maintenance start
  debug:
    msg: "Starting Zypper maintenance (openSUSE/SLES)"

- name: Refresh Zypper repositories
  zypper:
    name: "*"
    state: latest
    update_cache: yes
  register: zypper_refresh

- name: Upgrade all packages
  zypper:
    name: "*"
    state: latest
  register: zypper_upgrade

- name: Show upgraded packages count
  debug:
    msg: "Upgraded packages via Zypper"
  when: zypper_upgrade.changed

- name: Get list of unneeded packages
  command: zypper --non-interactive packages --unneeded
  register: zypper_unneeded
  changed_when: false
  failed_when: false

- name: Remove unnecessary packages
  command: zypper --non-interactive remove --clean-deps {{ item }}
  loop: "{{ zypper_unneeded.stdout_lines | select('match', '^i \\| .*') | map('regex_replace', '^i \\| ([^ ]+) .*', '\\1') | list }}"
  when: zypper_unneeded.rc == 0 and zypper_unneeded.stdout_lines | length > 0
  register: zypper_autoremove
  failed_when: false

- name: Clean Zypper cache
  command: zypper --non-interactive clean --all
  changed_when: true

- name: Zypper maintenance complete
  debug:
    msg: "Zypper maintenance completed"