---
- name: Zypper maintenance start
  debug:
    msg: "Starting Zypper maintenance (openSUSE/SLES)"

- name: Refresh Zypper repositories
  zypper:
    name: "*"
    state: latest
    update_cache: yes
  register: zypper_refresh

- name: Upgrade all packages
  zypper:
    name: "*"
    state: latest
  register: zypper_upgrade

- name: Show upgraded packages count
  debug:
    msg: "Upgraded packages via Zypper"
  when: zypper_upgrade.changed

- name: Remove unnecessary packages
  command: zypper packages --unneeded | awk -F'|' 'NR==0 || NR==1 || NR==2 || NR==3 || NR==4 {next} {print $3}' | grep -v Name | xargs -r zypper remove --clean-deps -y
  register: zypper_autoremove
  changed_when: zypper_autoremove.rc == 0
  failed_when: false

- name: Clean Zypper cache
  command: zypper clean --all
  changed_when: true

- name: Zypper maintenance complete
  debug:
    msg: "Zypper maintenance completed"
